# Generated by Django 4.2 on 2024-12-01 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloguser',
            options={},
        ),
        migrations.AlterModelTable(
            name='bloguser',
            table='blog_user',
        ),
    ]
